### ISSUE TITLE
User Can Enter Site

### ISSUE THREAD

**Issue by MeganHuggins** [Hifu-devs/hifu-mobile#4]
**Happy Path:**
As a User, when I open the app I am greeted by the /Home page. When I click the Start Trip button I am redirected to the /Information page

_Chores:_
- [x] [Set Up React Navigation](https://github.com/Hifu-devs/hifu-mobile/issues/19)
- [x] [Set Up Landing Page](https://github.com/Hifu-devs/hifu-mobile/issues/21)
- [x] [Style Out Landing Page](https://github.com/Hifu-devs/hifu-mobile/issues/20)
- [x] [Set Up Information/Form Page](https://github.com/Hifu-devs/hifu-mobile/issues/22)
