### ISSUE TITLE
User Can Move To /Map Page

### ISSUE THREAD

**Issue by MeganHuggins** [Hifu-devs/hifu-mobile#7]
**Happy Path:**
- [x] As a User, once I have finished and saved the info form, I click on the Map navigation tab and am brought to a Map 

**Sad Path:**
- [x] As a User, while on the information page I click on the Map navigation tab I am met with a warning to fill out and save information form 

_Chores:_
- [x] [Set Up SearchBar Component](https://github.com/Hifu-devs/hifu-mobile/issues/25)
- [x] [Style Out SearchBar](https://github.com/Hifu-devs/hifu-mobile/issues/28)
- [x] [SearchBar Functionality](https://github.com/Hifu-devs/hifu-mobile/issues/27)
- [x] [Set Up Map Page](https://github.com/Hifu-devs/hifu-mobile/issues/29)
